version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    tmpfs:
      - /run
      - /var/cache
      - /tmp
    volumes:
      - .:/app
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
